### PR TITLE
Fix build with latest sdformat11 branch

### PR DESCRIPTION
**Pull request by chapulina**
The const-correctness introduced in https://github.com/osrf/sdformat/pull/474 broke `ign-gazebo`. I originally thought this was a Windows-only issue, but it turns out it manifested first on Windows because CI builds SDFormat from source.

### CODE REVIEW

File: src/Conversions.cc [hunk 1]
```diff
@@ -274,11 +274,11 @@ msgs::Material ignition::gazebo::convert(const sdf::Material &_in)
   out.set_lighting(_in.Lighting());
   out.set_double_sided(_in.DoubleSided());
 
-  sdf::Pbr *pbr = _in.PbrMaterial();
+  auto pbr = _in.PbrMaterial();
   if (pbr)
   {
-    msgs::Material::PBR *pbrMsg = out.mutable_pbr();
-    sdf::PbrWorkflow *workflow = pbr->Workflow(sdf::PbrWorkflowType::METAL);
+    auto pbrMsg = out.mutable_pbr();
```
Comment (sloretz) [inline src/Conversions.cc:280]: This type's const-ness was already correct.

File: src/Model.cc [hunk 2]
```diff
@@ -33,7 +33,8 @@ class ignition::gazebo::ModelPrivate
   public: Entity id{kNullEntity};
 };
 
-using namespace ignition::gazebo;
+using namespace ignition;
+using namespace gazebo;
```
Comment (sloretz) [inline src/Model.cc:37]: Will anything this file includes ever be in the `gazebo` namespace? If so, it looks like splitting the using declaration would cause a compile error.

```
#include <iostream>

namespace gazebo
{
  void say_hello() { std::cout << "Hello from gazebo::say_hi()\n";}
}

namespace ignition
{
namespace gazebo
{
  void say_hi() { std::cout << "Hi from ignition::gazebo::say_hi()\n";}
}
}


// using namespace ignition::gazebo;
using namespace ignition;
using namespace gazebo;

int main()
{

  say_hello();
  say_hi();
  return 0;
}
```

```console
$ g++ -std=c++14 test.cpp
test.cpp:19:17: error: reference to ‘gazebo’ is ambiguous
 using namespace gazebo;
[...]
```

File: src/systems/user_commands/UserCommands.cc [hunk 3]
```diff
@@ -542,9 +542,9 @@ bool CreateCommand::Execute()
   }
   else if (isLight && isRoot)
   {
-    auto light = root.Light();
-    light->SetName(desiredName);
-    entity = this->iface->creator->CreateEntities(light);
+    auto light = *root.Light();
```
Comment (sloretz) [inline src/systems/user_commands/UserCommands.cc:545]: Hard to tell, does this cause a copy where there wasn't one before, or is `root.Light()` returning a reference?

File: src/Model.cc (hunk 2 above)
Comment (chapulina) [reply src/Model.cc:37]: I don't think that's a concern, we don't use any `gazebo` namespace outside of `ignition`.

File: src/systems/user_commands/UserCommands.cc (hunk 3 above)
Comment (chapulina) [reply src/systems/user_commands/UserCommands.cc:545]: Yeah the idea is to make a copy, because `Root::Light()` returns a const pointer. I think this is only a problem on Windows. As far as I can tell, that has been returning a const pointer since it was implemented and didn't cause issues on Linux or macOS. That line was introduced in #572, before we enabled Windows CI.

**Comment by chapulina** [comment]
I don't know why the Windows CI result is not coming back, but it built correctly. Test failures and warnings are expected.

[Build Status](https://build.osrfoundation.org/job/ign_gazebo-pr-win/2235/)

File: src/Conversions.cc (hunk 1 above)
Comment (chapulina) [reply src/Conversions.cc:280]: Oh you're right. I'm ok letting this through to save another round of CI.

**Review by caguero — APPROVED** [review]
Looks good to me.
